# Generated by Django 3.0.2 on 2020-01-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.CharField(default='get_current_user', help_text='The current user will be retrieved and put in this box', max_length=50)),
                ('project_per_usr', models.CharField(choices=[], help_text='projects based on current user', max_length=100)),
            ],
        ),
    ]
