# Generated by Django 3.0.2 on 2020-01-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20200127_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capuser',
            name='project_per_usr',
            field=models.CharField(blank=True, choices=[], help_text='projects based on current user', max_length=100),
        ),
    ]
