# Generated by Django 3.0.2 on 2020-01-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20200127_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capuser',
            name='current_user',
            field=models.CharField(help_text='The current user will be retrieved and put in this box', max_length=200),
        ),
    ]
